### ISSUE TITLE
[Enquiry] Planning to expand on this?

### ISSUE THREAD

**Issue by lf-araujo** [bzimmermandev/matrix#1]
This is already a very important part of running statistics in Swift, truly useful. Congratulations.

Are you planning to further expand on it? For example, create a supertype similar to [dataframe in R](http://www.r-tutor.com/r-introduction/data-frame)?

Edit: I also found this source for a matrix multiplication algorithm in Swift: https://github.com/raywenderlich/swift-algorithm-club/tree/master/Strassen%20Matrix%20Multiplication

**Comment by bzimmermandev** [comment]
Thank you very much, and sorry for the late response!

The short answer is no, sorry, the `Matrix` class won't be expanded. I haven't been actively coding in Swift at all. I hadn't really intended to implement matrix multiplication from the outset, as I was typically using `Matrix` for holding references to objects, more than anything else. It's useful for 2D game logic and other 2-dimensional domains as it is.

You're more than welcome to adopt the code. Just let me know, and I can transfer the repo over. (:

**Comment by lf-araujo** [comment]
Thank you
